import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import BottomNavbar from '@/components/common/nav/BottomNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-lg'>{children}</div>
        <BottomNavbar />
      </body>
    </html>
  )
}
