import type { Metadata } from "next"
import BottomNavbar from "@/components/common/nav/BottomNavbar"
import TopNavbar from "@/components/common/nav/TopNavbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="w-full min-h-screen bg-gray-100">
      <div className="max-w-lg mx-auto">
        <TopNavbar />
        {children}
      </div>
      <BottomNavbar />
    </div>
  )
}
